POST http://localhost:8080/board/create
content-type: application/json; charset=UTF-8

{
    "subject": "test1",
    "content": "테스트 내용입니다.",
    "writer": "test"
}

### 전체
GET http://localhost:8080/board

### 상세
GET http://localhost:8080/board/1

### 수정

PUT http://localhost:8080/board/update/8
content-Type: application/json; charset=UTF-8

{
    "subject": "test2",
    "content": "test3",
    "writer": "test2"
}